export const LOGGED_IN = 'LOGGED_IN';
export const USER_INFO_UPDATED = 'USER_INFO_UPDATED';
export const THREAD_ADDED = 'THREAD_ADDED';
export const THREAD_REMOVED = 'THREAD_REMOVED';
export const THREAD_MODIFIED = 'THREAD_MODIFIED';
export const THREADS_REORDERED = 'THREADS_REORDERED';
export const MESSAGE_ADDED = 'MESSAGE_ADDED';
